# Generated by Django 5.2.8 on 2025-11-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=12, unique=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveSmallIntegerField(null=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('pending', 'Pending'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('tnc', models.TextField(blank=True)),
            ],
        ),
    ]
