# Generated by Django 5.2.8 on 2025-11-15 15:18

import RentalMotor.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=RentalMotor.views.unified_image_path),
        ),
    ]
