# Generated by Django 5.2.8 on 2025-11-15 15:18

import RentalMotor.views
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_rental_admin_reason_rental_reviewed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='sim_image',
            field=models.ImageField(blank=True, null=True, upload_to=RentalMotor.views.unified_image_path),
        ),
    ]
