# Generated by Django 5.2.8 on 2025-11-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0004_rental_sim_image'),
        ('vehicles', '0003_alter_vehicle_image'),
    ]

    
