# Generated by Django 5.2.8 on 2025-11-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_delete_adminnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='vehicle',
        ),
    ]
